const categoryLabels = {
  foundation: '基础候选',
  subset: '数组与区块',
  wing: '翼形与矩形',
  fish: '鱼形',
  chain: '链与染色',
  als: 'ALS 与模板',
  special: '特殊结构',
}

export const techniqueGuides = [
  {
    id: 'last-cell',
    label: '最后空格',
    title: '最后空格：先找快要填满的区域',
    level: '初级',
    category: 'foundation',
    animated: true,
    aliases: ['Open Single', 'Full House'],
    summary: '一行、一列或一个宫只剩一个空格时，缺的那个数字没有选择余地。',
    rule: '只看一个区域，数出缺失的数字，把它填进唯一空格。',
    steps: ['先扫每一行，找只有一个空格的行。', '再用同样方法扫列和宫。', '确认这个区域缺的是哪一个数字。', '如果行、列、宫都不冲突，就可以填入。'],
    noviceTip: '这是最稳的入门技巧，不需要写候选数。做题前期可以快速清掉明显空格。',
    pitfalls: ['不要只看一行就填数，填入前仍要确认同列、同宫没有同样数字。'],
  },
  {
    id: 'naked-single',
    label: '唯一候选',
    title: '唯一候选：一个格只剩一个可能数字',
    level: '初级',
    category: 'foundation',
    animated: true,
    aliases: ['Naked Single'],
    summary: '某个空格被同行、同列、同宫排除后，只剩一个合法数字。',
    rule: '目标是格子本身：这个格还能写什么，只剩一个就填。',
    steps: ['选一个空格。', '列出 1 到 9 中没有被同行、同列、同宫占用的数字。', '如果列表只剩一个数字，它就是答案。'],
    noviceTip: '如果你开了智能余数，只有一个候选的小格就是唯一候选。',
    pitfalls: ['唯一候选看的是一个格，不是一个区域。不要和“唯一位置”混在一起。'],
  },
  {
    id: 'hidden-single',
    label: '唯一位置',
    title: '唯一位置：一个数字只剩一个落点',
    level: '初级',
    category: 'foundation',
    animated: true,
    aliases: ['Hidden Single'],
    summary: '一个数字在某行、列或宫里只剩一个格能放，即使那个格还有别的候选，也必须放这里。',
    rule: '目标是某个区域里的某个数字：这个数字只有一个位置，就填它。',
    steps: ['选定一个区域，比如第 4 行。', '挑一个还没出现的数字。', '检查这个数字能落在哪些空格。', '只剩一个落点时，填入该数字。'],
    noviceTip: '口诀是“数字找位置”，和唯一候选的“格子找数字”正好相反。',
    pitfalls: ['这个格可能还有多个候选，不能因为候选多就错过它。'],
  },
  {
    id: 'naked-pair',
    label: '裸对',
    title: '裸对：两个格锁定两个数字',
    level: '中级',
    category: 'subset',
    animated: true,
    aliases: ['Naked Pair', 'Locked Pair'],
    summary: '同一区域内两个格的候选完全相同且都只有两个，这两个数字只能占据这两个格。',
    rule: '从同一区域的其他格删除这两个候选。',
    steps: ['在一行、一列或一宫中找只有两个候选的格。', '确认有两格候选完全一样。', '把这两个数字从该区域其他格的候选中划掉。'],
    noviceTip: '裸对不是直接填数，而是清理候选，为下一步制造唯一候选或唯一位置。',
    pitfalls: ['两个格必须在同一个区域里；不同行、不同列、不同宫的相同候选不能直接形成裸对。'],
  },
  {
    id: 'hidden-pair',
    label: '隐对',
    title: '隐对：两个数字只藏在两个格里',
    level: '中级',
    category: 'subset',
    animated: true,
    aliases: ['Hidden Pair'],
    summary: '两个数字在一个区域中都只出现在相同的两个格里，这两个格就被这两个数字占住。',
    rule: '保留这两个数字，删除这两个格中的其他候选。',
    steps: ['按数字检查一个区域内的候选位置。', '找到两个数字的位置完全相同，并且只占两格。', '这两格只保留这两个数字。'],
    noviceTip: '隐对的格子里通常还有杂项候选，难点是按数字看位置，而不是按格看候选。',
    pitfalls: ['如果其中一个数字还出现在第三个格，就不是隐对。'],
  },
  {
    id: 'naked-triple',
    label: '裸三',
    title: '裸三：三个格锁定三个数字',
    level: '中级',
    category: 'subset',
    animated: true,
    aliases: ['Naked Triple', 'Locked Triple'],
    summary: '同一区域中三个格的候选并集刚好是三个数字，这三个数字只能在这三格中分配。',
    rule: '从同一区域其他格删除这三个候选。',
    steps: ['找候选数不超过三个的空格。', '任选三格，看它们的候选并集是否刚好三个数字。', '如果成立，删除区域内其他格的这些候选。'],
    noviceTip: '裸三不要求每格都有三个候选，2/2/2 或 2/2/3 也可能成立。',
    pitfalls: ['如果同一区域还有第四个格也只含这三个数字，这个三数组就不封闭。'],
  },
  {
    id: 'hidden-triple',
    label: '隐三',
    title: '隐三：三个数字只藏在三个格里',
    level: '中级',
    category: 'subset',
    animated: true,
    aliases: ['Hidden Triple'],
    summary: '三个数字在一个区域内的所有可能位置合起来正好是三个格。',
    rule: '这三格只保留这三个数字，删掉其他候选。',
    steps: ['选定一个区域。', '逐个数字记录候选位置。', '找三个数字，它们的位置并集只有三个格。', '删除这三格中不属于组合的候选。'],
    noviceTip: '隐三比裸三更难发现，适合在候选很多但某些数字位置很少时找。',
    pitfalls: ['只看格子候选很容易漏掉隐三，要反过来按数字统计位置。'],
  },
  {
    id: 'subset-quad',
    label: '四数组',
    title: '四数组：裸四与隐四的入门理解',
    level: '高级',
    category: 'subset',
    aliases: ['Naked Quadruple', 'Hidden Quadruple'],
    summary: '四数组是裸对、裸三、隐对、隐三的自然扩展，只是规模从两个或三个变成四个。',
    rule: '裸四删除区域其他格中的四个数字；隐四删除四个格中不属于组合的候选。',
    steps: ['先确认只在同一行、列或宫内讨论。', '裸四看四个格的候选并集是否刚好四个数字。', '隐四看四个数字的候选位置并集是否刚好四个格。', '成立后只做候选删除，通常不会立刻填数。'],
    noviceTip: '四数组出现频率低。新手不必硬找，等候选被其他技巧清理后再回头看。',
    pitfalls: ['不要跨区域拼四格；数组技巧必须在一个共同区域里成立。'],
  },
  {
    id: 'pointing',
    label: '指向',
    title: '指向：宫里的候选被锁到一条线',
    level: '高级',
    category: 'subset',
    animated: true,
    aliases: ['Locked Candidate', 'Locked Candidates', 'Locked Candidates Type 1 (Pointing)', 'Pointing'],
    summary: '某个数字在一个宫里的候选都落在同一行或同一列，它就会“指向”这条线。',
    rule: '从这条线中、宫外的其他格删除同一个候选。',
    steps: ['选择一个宫和一个候选数字。', '确认这个数字在宫内的所有候选共线。', '沿这条行或列向宫外看，删掉同数字候选。'],
    noviceTip: '指向从“宫”出发，往“行或列”外面删。',
    pitfalls: ['宫内候选必须全部共线，只看到两个共线还不够，第三个候选若不共线就不能用。'],
  },
  {
    id: 'claiming',
    label: '区块削减',
    title: '区块削减：一条线把候选锁进一个宫',
    level: '中级',
    category: 'subset',
    animated: true,
    aliases: ['Claiming Candidate', 'Locked Candidates Type 2 (Claiming)', 'Claiming'],
    summary: '某个数字在一行或一列中的候选全部位于同一个宫内，这条线就“声明”该宫里的落点。',
    rule: '从该宫中、不在这条线上的格删除同一个候选。',
    steps: ['选择一行或一列和一个候选数字。', '确认这条线上的该候选全部落在同一个宫。', '在这个宫内删除线外的同数字候选。'],
    noviceTip: '区块削减从“行或列”出发，往“宫”里面删。',
    pitfalls: ['它和指向方向相反，但本质都是区块排除。'],
  },
  {
    id: 'x-wing',
    label: 'X-Wing',
    title: 'X-Wing：两行两列组成矩形',
    level: '高级',
    category: 'fish',
    animated: true,
    aliases: ['X-Wing'],
    summary: '同一候选在两条基础行中只出现在相同两列，这两列就被锁定。',
    rule: '从覆盖列的其他格删除该候选；行列可以互换。',
    steps: ['固定一个数字。', '找该数字只出现两处候选的行。', '如果两行的候选列完全相同，就形成矩形。', '删除这两列其他行的同数字候选。'],
    noviceTip: '先固定数字再找图形，比在全盘乱看矩形更容易。',
    pitfalls: ['两行的候选列必须一样；只形成普通矩形但每行还有第三处候选，就不是 X-Wing。'],
  },
  {
    id: 'swordfish',
    label: '剑鱼',
    title: 'Swordfish：三行三列的鱼形结构',
    level: '专家',
    category: 'fish',
    animated: true,
    aliases: ['Swordfish'],
    summary: '三条基础行中的同一候选，被限制在同三条覆盖列内。',
    rule: '从覆盖列中、不属于基础行的格删除该候选；行列可以互换。',
    steps: ['固定一个候选数字。', '找候选位置不超过三处的行。', '选三行，确认候选列的并集刚好三列。', '删除三列其他行的同数字候选。'],
    noviceTip: '可以把它理解成更大的 X-Wing：2x2 变成 3x3。',
    pitfalls: ['基础行可以每行两处或三处候选，但三行合起来的覆盖列必须正好三列。'],
  },
  {
    id: 'jellyfish',
    label: '水母',
    title: 'Jellyfish：四行四列的鱼形结构',
    level: '专家',
    category: 'fish',
    animated: true,
    aliases: ['Jellyfish'],
    summary: '四条基础行中的同一候选，被限制在同四条覆盖列内。',
    rule: '从覆盖列中、不属于基础行的格删除该候选；行列可以互换。',
    steps: ['固定一个候选。', '找候选位置不超过四处的行。', '选四行，确认候选列并集正好四列。', '删除四列其他行的同候选。'],
    noviceTip: '水母很少见，通常交给提示引擎识别即可。理解时抓住“基础线数量等于覆盖线数量”。',
    pitfalls: ['不要被名字吓到，它仍然只是鱼形封锁。'],
  },
  {
    id: 'fish-family',
    label: '高级鱼形',
    title: '高级鱼形：大鱼、鳍鱼、变形鱼',
    level: '专家',
    category: 'fish',
    aliases: ['Squirmbag', 'Whale', 'Leviathan', 'Finned X-Wing', 'Finned Swordfish', 'Finned Jellyfish', 'Finned Squirmbag', 'Finned Whale', 'Finned Leviathan', 'Sashimi X-Wing', 'Sashimi Swordfish', 'Sashimi Jellyfish', 'Sashimi Squirmbag', 'Sashimi Whale', 'Sashimi Leviathan', 'Franken X-Wing', 'Franken Swordfish', 'Franken Jellyfish', 'Franken Squirmbag', 'Franken Whale', 'Franken Leviathan', 'Finned Franken X-Wing', 'Finned Franken Swordfish', 'Finned Franken Jellyfish', 'Finned Franken Squirmbag', 'Finned Franken Whale', 'Finned Franken Leviathan', 'Mutant X-Wing', 'Mutant Swordfish', 'Mutant Jellyfish', 'Mutant Squirmbag', 'Mutant Whale', 'Mutant Leviathan', 'Finned Mutant X-Wing', 'Finned Mutant Swordfish', 'Finned Mutant Jellyfish', 'Finned Mutant Squirmbag', 'Finned Mutant Whale', 'Finned Mutant Leviathan', 'Kraken Fish', 'Kraken Fish Type 1', 'Kraken Fish Type 2'],
    summary: '这些都是鱼形家族的扩展：基础区域和覆盖区域共同限制同一个候选。',
    rule: '先证明候选必须占据一组覆盖区域，再删除不可能共存的候选。',
    steps: ['固定一个数字，不要同时看多个数字。', '找候选被少数区域限制的行、列或宫。', '普通大鱼要求基础区域数等于覆盖区域数。', '鳍鱼多出少量“鳍”，删除时只删能同时看到鳍和鱼身结论的候选。'],
    noviceTip: '新手先学 X-Wing、剑鱼、水母即可。高级鱼形更多是理解提示为什么能删候选。',
    pitfalls: ['鳍鱼不能像普通鱼一样整列整行删除，删除范围更窄。'],
  },
  {
    id: 'y-wing',
    label: 'Y-Wing',
    title: 'Y-Wing：枢轴连接两个翼格',
    level: '高级',
    category: 'wing',
    animated: true,
    aliases: ['Y-Wing', 'XY-Wing'],
    summary: '三个双候选格形成 AB、AC、BC。枢轴不管取 A 还是 B，两个翼格总有一个会取 C。',
    rule: '从同时能看到两个翼格的格中删除候选 C。',
    steps: ['找一个双候选枢轴 AB。', '找能看到枢轴的两个翼格 AC 和 BC。', '确定两翼都含同一个待删数字 C。', '删除两翼共同影响位置中的 C。'],
    noviceTip: 'Y-Wing 的关键不是形状像 Y，而是三个双候选格之间的“二选一”。',
    pitfalls: ['待删格必须同时看到两个翼格，只看到枢轴没有用。'],
  },
  {
    id: 'xyz-wing',
    label: 'XYZ-Wing',
    title: 'XYZ-Wing：三候选枢轴连接两个翼格',
    level: '专家',
    category: 'wing',
    animated: true,
    aliases: ['XYZ-Wing'],
    summary: '枢轴有 XYZ 三个候选，两个翼格分别是 XZ 与 YZ，三格至少有一个会是 Z。',
    rule: '从同时能看到枢轴和两个翼格的格中删除 Z。',
    steps: ['找一个三候选枢轴 XYZ。', '找两个双候选翼格 XZ 和 YZ。', '确认两翼都能看到枢轴。', '在三格共同影响范围删除 Z。'],
    noviceTip: 'XYZ-Wing 比 Y-Wing 多要求待删格也能看到枢轴。',
    pitfalls: ['如果目标格只看到两个翼格但看不到枢轴，那是 Y-Wing 的删除条件，不是 XYZ-Wing。'],
  },
  {
    id: 'w-wing',
    label: 'W-Wing',
    title: 'W-Wing：两个相同双候选用强链连接',
    level: '专家',
    category: 'wing',
    aliases: ['W-Wing'],
    summary: '两个相同双候选格 AB 之间，通过某个数字的一条强链证明它们不可能同时不是另一个数字。',
    rule: '从同时看到两个端点的格中删除共同候选。',
    steps: ['找两个候选完全相同的双候选格。', '寻找其中一个数字在某行、列或宫中的强链。', '用强链证明两个端点至少有一个取另一个共同数字。', '删除同时看到两个端点的这个共同候选。'],
    noviceTip: '把它当成“带一条连接线的翼形技巧”，先找双候选端点，再找强链。',
    pitfalls: ['连接必须是强链，也就是该数字在一个区域内只剩两个位置。'],
  },
  {
    id: 'skyscraper',
    label: '摩天楼',
    title: 'Skyscraper：两条强链竖起两个楼顶',
    level: '高级',
    category: 'chain',
    animated: true,
    aliases: ['Skyscraper'],
    summary: '同一候选在两条行或列强链中各剩两个位置，其中一端对齐，另外两个外端至少一个为真。',
    rule: '从同时能看到两个外端的格中删除该候选。',
    steps: ['固定一个候选。', '找两条行强链或两条列强链。', '确认两条链有一端在同一列或同一行。', '删除两个不对齐外端共同影响范围中的候选。'],
    noviceTip: '摩天楼可以看成很短的 X-Chain。',
    pitfalls: ['两个外端如果互相能看到，结构通常退化，删除条件要重新检查。'],
  },
  {
    id: 'two-string-kite',
    label: '双线风筝',
    title: '双线风筝：行强链连接列强链',
    level: '高级',
    category: 'chain',
    animated: true,
    aliases: ['Two-String Kite', '2-String Kite'],
    summary: '一条行强链和一条列强链在同一个宫里相连，两个宫外端点至少有一个为真。',
    rule: '从同时能看到两个宫外端点的格中删除该候选。',
    steps: ['固定一个候选。', '找一条行强链和一条列强链。', '确认它们各有一端落在同一个宫。', '删除两个外端共同影响位置中的候选。'],
    noviceTip: '先找“只剩两个位置”的行和列，再看它们能不能在一个宫内接上。',
    pitfalls: ['宫内两个连接端不必是同一个格，但必须在同一个宫。'],
  },
  {
    id: 'empty-rectangle',
    label: '空矩形',
    title: 'Empty Rectangle：宫内候选形成空角',
    level: '专家',
    category: 'chain',
    aliases: ['Empty Rectangle', 'Dual Empty Rectangle', 'Turbot Fish', 'Dual 2-String Kite'],
    summary: '空矩形、Turbot Fish 和部分双结构，都是用同一候选的强弱关系推出某个候选不能成立。',
    rule: '找到宫内的矩形空角，再结合一条强链删除共同影响位置的候选。',
    steps: ['固定一个候选数字。', '在一个宫中找候选只分布在一行加一列的形态。', '用宫外的一条强链连接其中一端。', '删除被两个结论端同时限制的候选。'],
    noviceTip: '它比指向复杂，因为还要额外接一条强链。先会摩天楼和双线风筝会更容易理解。',
    pitfalls: ['只看到宫内 L 形并不能直接删除，必须有外部强链配合。'],
  },
  {
    id: 'chain-aic',
    label: '链与 AIC',
    title: '链与 AIC：把“如果不是它就必须是它”连起来',
    level: '专家',
    category: 'chain',
    animated: true,
    aliases: ['X-Chain', 'XY-Chain', 'Remote Pair', 'Nice Loop/AIC', 'Continuous Nice Loop', 'Discontinuous Nice Loop', 'Grouped Nice Loop/AIC', 'Grouped Continuous Nice Loop', 'Grouped Discontinuous Nice Loop', 'AIC', 'Grouped AIC'],
    summary: '链技巧把候选之间的强关系和弱关系按顺序连起来。读链时不要先看整盘，先沿箭头读每个候选数字：实线是强关系，虚线是弱关系。',
    rule: '如果链能证明两个端点里至少有一个必定成立，那么任何同时看到这两个端点的格，都不能再填端点的那个候选。',
    steps: ['先固定链的端点候选。本例端点都是候选 9：第 1 行第 1 列的 9，以及第 5 行第 3 列的 9。', '强关系表示“两端至少一个成立”。它可以在同一个双候选格里，也可以在同一行、列或宫的两个同候选位置之间。', '弱关系表示“两端不能同时成立”。常见情况是两个互相看见的格共享同一个候选。', '强、弱关系按箭头读到最后，只需要确认端点结论：第 1 行第 1 列的 9 和第 5 行第 3 列的 9 至少有一个成立。', '找同时能看到两个端点的格。本例第 1 行第 3 列同时看见两个端点，所以它可以排除 9。'],
    example: {
      title: '跟着动画里的这条链读一遍',
      setup: '动画例子要删除第 1 行第 3 列的 9。原因不是这个格自己很特殊，而是它同时受到链两端的限制。',
      chain: [
        '第 1 行第 1 列只有候选 2、9。实线从 9 指向 2，这是格内强关系：如果它不是 9，就必须是 2。',
        '虚线从第 1 行第 1 列的 2 指向第 1 行第 8 列的 2：这两个 2 同行，不能同时成立。于是第 1 行第 8 列只剩 1，实线切到 1。',
        '虚线从第 1 行第 8 列的 1 指向第 3 行第 7 列的 1：这两个 1 同宫，不能同时成立。于是第 3 行第 7 列只剩 7，实线切到 7。',
        '虚线从第 3 行第 7 列的 7 指向第 2 行第 7 列的 7：这两个 7 同列，不能同时成立。',
        '实线从第 2 行第 7 列的 5 指向第 2 行第 2 列的 5，这是格间强关系：本例第 2 行里候选 5 只剩这两个位置，所以两个 5 至少有一个成立。',
        '第 2 行第 2 列只有 5、9。实线从 5 切到 9，再用虚线连接到第 5 行第 3 列的 9，得到右端点。',
      ],
      conclusion: '这条链的意思是：第 1 行第 1 列的 9 和第 5 行第 3 列的 9 至少有一个成立。第 1 行第 3 列同时看见左端点同行、右端点同列，因此第 1 行第 3 列不能填 9。',
    },
    noviceTip: '读提示时按编号箭头走，不要试图一次看懂整张图。先确认“两个端点至少一个成立”，再检查被删除的格是否同时能看到这两个端点。',
    pitfalls: ['链关系必须按顺序成立；随意把能看见的候选连起来不能保证结论成立。', '删除目标必须同时看到两个端点，只看到其中一个端点不能删除。'],
  },
  {
    id: 'coloring',
    label: '染色',
    title: '染色：给同一候选的强链网络分两种颜色',
    level: '专家',
    category: 'chain',
    aliases: ['Simple Colors', 'Simple Colors Trap', 'Simple Colors Wrap', 'Multi Colors', 'Multi Colors 1', 'Multi Colors 2'],
    summary: '染色把同一候选的强链端点交替标色。如果一种颜色自相矛盾，或某格同时看到两种颜色，就能删除候选。',
    rule: '同色冲突时删掉整种颜色；目标格同时看到两色时，目标格可删该候选。',
    steps: ['固定一个候选数字。', '找所有强链，把两端交替染成两种颜色。', '检查同色是否在同一区域冲突。', '检查未染色候选是否同时看到两种颜色。'],
    noviceTip: '染色只处理一个数字，适合候选图比较稀疏的时候。',
    pitfalls: ['弱链不能直接参与简单染色；多重染色需要处理两组颜色之间的关系。'],
  },
  {
    id: 'forcing',
    label: '强制推理',
    title: '强制链与强制网：分支试探但仍可解释',
    level: '专家',
    category: 'chain',
    aliases: ['Forcing Chain', 'Forcing Chain Contradiction', 'Forcing Chain Verity', 'Forcing Net', 'Forcing Net Contradiction', 'Forcing Net Verity', 'Nishio'],
    summary: '强制推理从一个候选的真假分支出发，沿逻辑一路推出结论或矛盾。',
    rule: '如果一个分支导致矛盾，就排除这个分支；如果两个分支都推出同一结论，这个结论成立。',
    steps: ['选择一个关键候选作为起点。', '分别假设它为真或为假。', '沿唯一候选、强链、区块等逻辑推进。', '寻找矛盾或两个分支共同结论。'],
    noviceTip: '它比普通链更像“有记录的试探”。能读懂结论即可，不必手工频繁使用。',
    pitfalls: ['强制推理不是随便猜答案；每一步仍要有可验证的逻辑依据。'],
  },
  {
    id: 'unique-rectangle',
    label: '唯一矩形',
    title: '唯一矩形：避免出现两个解的矩形陷阱',
    level: '专家',
    category: 'wing',
    aliases: ['Uniqueness Test 1', 'Uniqueness Test 2', 'Uniqueness Test 3', 'Uniqueness Test 4', 'Uniqueness Test 5', 'Uniqueness Test 6', 'Hidden Rectangle', 'Avoidable Rectangle Type 1', 'Avoidable Rectangle Type 2'],
    summary: '唯一矩形利用正规数独只有唯一解的前提，避免四个格在两行、两列、两宫中只剩同一对数字。',
    rule: '如果某个候选会造成可互换的双解矩形，就排除它。',
    steps: ['找横跨两行、两列、两个宫的四个角。', '确认四角围绕同一对数字。', '检查哪一个角或哪几个角多出额外候选。', '按对应类型删除会造成双解的候选。'],
    noviceTip: '使用前要确认题目本身是唯一解。多数正规题库满足这个前提。',
    pitfalls: ['四个角必须只跨两个宫，不是任意 2x2 矩形都能用。'],
  },
  {
    id: 'bug-plus-one',
    label: 'BUG+1',
    title: 'BUG+1：唯一解原则下的最后异常格',
    level: '专家',
    category: 'special',
    aliases: ['Bivalue Universal Grave + 1', 'BUG+1'],
    summary: '当所有未解格几乎都是双候选，只有一个格有三个候选时，唯一解要求这个异常格必须取特定数字。',
    rule: '找出在全盘候选出现次数不平衡的数字，将异常格确定为它。',
    steps: ['确认除一个格外，其他未解格都是双候选。', '检查每个数字在每行、列、宫中的候选出现次数。', '找到异常格中能打破双解结构的候选。', '填入该候选。'],
    noviceTip: 'BUG+1 很靠后，通常出现在盘面已经非常干净的时候。',
    pitfalls: ['候选没有完整整理时不要用 BUG+1。'],
  },
  {
    id: 'als',
    label: 'ALS',
    title: 'ALS：差一个就锁死的候选集合',
    level: '专家',
    category: 'als',
    aliases: ['Almost Locked Set XZ-Rule', 'Almost Locked Set XY-Wing', 'Almost Locked Set XY-Chain', 'Death Blossom', 'Sue de Coq'],
    summary: 'ALS 是“n 个格里有 n+1 个候选”的集合。两个或多个 ALS 通过受限共同候选连接后，可以推出删除。',
    rule: '共同候选负责连接集合，另一个共同数字负责在集合外删除。',
    steps: ['在一个区域或相互关联的格中找 ALS。', '确认两个 ALS 之间有受限共同候选，也就是这个候选不能在两边同时成立。', '寻找两边都含有的另一个候选。', '删除同时看到两边该候选所有位置的外部候选。'],
    noviceTip: 'ALS 很抽象，可以先把它理解成“还差一格就会变成裸数组”的候选包。',
    pitfalls: ['受限共同候选和被删除候选不是同一个角色，混淆后很容易误删。'],
  },
  {
    id: 'templates',
    label: '模板',
    title: '模板法：枚举一个数字的所有完整摆法',
    level: '专家',
    category: 'als',
    aliases: ['Template Set', 'Template Delete'],
    summary: '模板法固定一个数字，枚举它在九行九列九宫中所有可能的完整分布，再看哪些候选在所有模板中都出现或都不出现。',
    rule: '所有模板都包含的位置可以确定；没有任何模板包含的位置可以删除。',
    steps: ['固定一个数字。', '列出这个数字满足行、列、宫约束的所有可行摆法。', '比较所有模板的共同点和排除点。', '据此填数或删候选。'],
    noviceTip: '模板法更适合程序提示，人工做题时可以把它当作高级验证工具。',
    pitfalls: ['模板只针对一个数字，不能把不同数字的模板混在一起推理。'],
  },
  {
    id: 'junior-exocet',
    label: 'Exocet',
    title: 'Junior Exocet：两个基格约束两个目标格',
    level: '专家',
    category: 'special',
    animated: true,
    aliases: ['Junior Exocet'],
    summary: '两个基格的候选集合，通过目标格、伴随格和交叉线的覆盖条件，限制目标格只能取基数。',
    rule: '从目标格删除不属于基数集合的候选。',
    steps: ['找同宫同线的两个基格。', '确定基数集合。', '检查两个目标格和两个伴随格。', '验证交叉线覆盖条件后，在目标格删除非基数。'],
    noviceTip: '这是非常高级的结构。教程重点是读懂提示中的基格、基数、目标格和交叉线。',
    pitfalls: ['Exocet 条件很严格，不要只凭形状判断。'],
  },
  {
    id: 'search',
    label: '搜索',
    title: '搜索：逻辑提示走不动时的完整验证',
    level: '专家',
    category: 'special',
    aliases: ['Brute Force', 'Incomplete Solution', 'Give Up'],
    summary: '搜索不是人类技巧，而是程序在逻辑策略没有继续结果时，用分支枚举确认下一步或完整解。',
    rule: '它可以验证答案，但不提供像候选技巧那样优雅的人工推理。',
    steps: ['选择候选最少的空格。', '尝试一个候选并继续求解。', '遇到矛盾就回溯。', '如果所有逻辑技巧都失败，搜索可用于确认题目可解性。'],
    noviceTip: '看到搜索提示时，可以先回到候选整理，寻找是否漏掉了前面的中高级技巧。',
    pitfalls: ['不要把搜索当作学习目标；它更像兜底工具。'],
  },
]

export const groupedTechniqueGuides = Object.entries(categoryLabels).map(([id, label]) => ({
  id,
  label,
  guides: techniqueGuides.filter((guide) => guide.category === id),
})).filter((group) => group.guides.length)

const normal = (value = '') => String(value).trim().toLowerCase().replace(/[\s_]+/g, '-')
const compact = (value = '') => normal(value).replace(/[^a-z0-9一-龥+-]/g, '')
const guideById = new Map(techniqueGuides.map((guide) => [guide.id, guide]))
const aliasToId = new Map()

for (const guide of techniqueGuides) {
  for (const name of [guide.id, guide.label, guide.title, ...(guide.aliases || [])]) {
    aliasToId.set(compact(name), guide.id)
  }
}

export function getTechniqueGuide(id) {
  return guideById.get(id) || null
}

export function findTechniqueGuide(strategy) {
  const key = compact(strategy)
  if (!key) return null
  const direct = aliasToId.get(key)
  if (direct) return getTechniqueGuide(direct)
  if (/locked-candidates.*pointing/.test(key)) return getTechniqueGuide('pointing')
  if (/locked-candidates.*claiming/.test(key)) return getTechniqueGuide('claiming')
  if (/uniqueness-test|unique-rectangle|avoidable-rectangle|hidden-rectangle/.test(key)) return getTechniqueGuide('unique-rectangle')
  if (/bug|bivalue-universal-grave/.test(key)) return getTechniqueGuide('bug-plus-one')
  if (/finned|sashimi|franken|mutant|squirmbag|whale|leviathan|kraken-fish/.test(key)) return getTechniqueGuide('fish-family')
  if (/als|almost-locked-set|death-blossom|sue-de-coq/.test(key)) return getTechniqueGuide('als')
  if (/template/.test(key)) return getTechniqueGuide('templates')
  if (/colors|colour/.test(key)) return getTechniqueGuide('coloring')
  if (/chain|aic|loop|remote-pair/.test(key)) return getTechniqueGuide('chain-aic')
  if (/forcing|nishio/.test(key)) return getTechniqueGuide('forcing')
  if (/brute-force|incomplete-solution|give-up|search/.test(key)) return getTechniqueGuide('search')
  return null
}

export function techniqueGuidePath(strategy) {
  const guide = findTechniqueGuide(strategy)
  return guide ? `/techniques/${guide.id}` : ''
}
